all: day01 day02 day03

day01: 
	gcc 01/a.c -o ./bin/01a
	./bin/01a 01/input.txt

	gcc 01/b.c -o ./bin/01b
	./bin/01b 01/input.txt

day02:
	gcc 02/a.c -o ./bin/02a
	./bin/02a 02/input.txt

	gcc 02/b.c -o ./bin/02b
	./bin/02b 02/input.txt

day03:
	gcc 03/a.c -o ./bin/03a
	./bin/03a 03/input.txt

	gcc 03/b.c -o ./bin/03b
	./bin/03b 03/input.txt
