all: day01 day02 day03 day04 day05 day06 day07 day08 day09 day10

day01: 
	gcc 01/a.c -o ./bin/01a
	./bin/01a 01/input.txt

	gcc 01/b.c -o ./bin/01b
	./bin/01b 01/input.txt

day02:
	gcc 02/a.c -o ./bin/02a
	./bin/02a 02/input.txt

	gcc 02/b.c -o ./bin/02b
	./bin/02b 02/input.txt

day03:
	gcc 03/a.c -o ./bin/03a
	./bin/03a 03/input.txt

	gcc 03/b.c -o ./bin/03b
	./bin/03b 03/input.txt

day04:
	gcc 04/a.c -lssl -lcrypto -o ./bin/04a
	./bin/04a iwrupvqb

	gcc 04/b.c -lssl -lcrypto -o ./bin/04b
	./bin/04b iwrupvqb

day05:
	gcc 05/a.c -o ./bin/05a
	./bin/05a ./05/input.txt

	gcc 05/b.c -o ./bin/05b
	./bin/05b ./05/input.txt

day06:
	gcc 06/a.c -o ./bin/06a
	./bin/06a ./06/input.txt

	gcc 06/b.c -o ./bin/06b
	./bin/06b ./06/input.txt

day07:
	gcc 07/a.c -Wall -o ./bin/07a
	./bin/07a ./07/input.txt

	gcc 07/b.c -Wall -o ./bin/07b
	./bin/07b ./07/input.txt

day08:
	gcc 08/a.c -Wall -o ./bin/08a
	./bin/08a ./08/input.txt

	gcc 08/b.c -Wall -o ./bin/08b
	./bin/08b ./08/input.txt

day09:
	gcc 09/a.c -Wall -o ./bin/09a
	./bin/09a ./09/input.txt

	gcc 09/b.c -Wall -o ./bin/09b
	./bin/09b ./09/input.txt

day10:
	gcc 10/a.c -Wall -o ./bin/10a
	./bin/10a 3113322113 40
	./bin/10a 3113322113 50
